### ISSUE TITLE
Linkout methods for collections

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/microservices#604]
I would like to request additional linkout methods to generate links to data collections at the Mines and at the Datastore. This would be be used at least for queries for genetic (qtl and gwas) studies (for which @That-Thing has web component implementations, sans linkouts).

Possibly these could be handled under a single method - but the parameters are not identical. At least initially, I'll suggest two separate methods -- one linking to mine pages and one to the Datastore.

```
collection_linkouts:
  DATA_TYPE: gwas
  GENUS: glycine
  COLLECTION_NAME: mixed.gwas.Cao_Li_2017
  Returns: https://mines.legumeinfo.org/glycinemine/gwas:mixed.gwas.Cao_Li_2017

  DATA_TYPE: qtlstudy
  GENUS: glycine
  COLLECTION_NAME: 0518BW-8_x_0734BW-1.qtl.Oyoo_Benitez_2011
  Returns: https://mines.legumeinfo.org/glycinemine/qtlstudy:0518BW-8_x_0734BW-1.qtl.Oyoo_Benitez_2011

  -
    method: GET
    href: https://mines.legumeinfo.org/glycinemine/{DATA_TYPE}:{COLLECTION_NAME}
    text: "View {COLLECTION_NAME} in LegumeMine"


datastore_linkouts:
  DATA_TYPE: gwas
  GENUS: Glycine
  SPECIES: max
  COLLECTION_NAME: mixed.gwas.Cao_Li_2017
  Returns: https://data.legumeinfo.org/Glycine/max/gwas/mixed.gwas.Cao_Li_2017

  DATA_TYPE: qtl
  COLLECTION_NAME: 0518BW-8_x_0734BW-1.qtl.Oyoo_Benitez_2011
  Returns: https://data.legumeinfo.org/Glycine/max/qtl/0518BW-8_x_0734BW-1.qtl.Oyoo_Benitez_2011

  -
    method: GET
    href: https://data.legumeinfo.org/{GENUS}/{SPECIES}/{DATA_TYPE}/{COLLECTION_NAME}
    text: "View {COLLECTION_NAME} in the LIS/SoyBase/PeanutBase Data Store
```

@alancleary @adf-ncgr @sammyjava @That-Thing @ctcncgr
